server:
    port: 8081
keycloak:
    auth-server-url: http://127.0.0.1:8080/auth
    realm: keycloak-demo
    resource: spring-boot-mvc-app
    public-client: true
    principal-attribute: preferred_username

spring:
    main:
        allow-bean-definition-overriding: true
#oauth2:
#    signature-verification:
#        public-key-endpoint-uri: http://localhost:9999/oauth/token
#management:
#    endpoints:
#        web:
#            exposure:
#                include:
#                    - metrics
#                    - prometheus