video:
  location: /home/saman/Videos
server:
  port: 9086

spring:
  application:
    name: webflix-streaming-service
  thymeleaf:
    cache: false
  webflux:
    static-path-pattern: /**
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/demo
        registration:
          keycloak:
            client-id: streamer
logging:
  level:
    org.springframework: info
management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus

